format_version: 10
common:
  serviceBuild: &serviceBuild
    - build:
        clean_workspace: true
        jobs:
          Build:
            artifacts:
              - build:
                  source: artifacts/buildReport.txt
              - build:
                  source: artifacts/buildReport.json
            elastic_profile_id: gocd-test-agent-dind
            environment_variables:
              CERTIFAI_BRANCH: develop
            tasks:
              - fetch:
                  pipeline: certifai-toolkit
                  stage: build
                  job: build
                  source: certifai_toolkit.zip
                  is_file: yes
              # TODO: Run c12e-ci to test examples before building templates
              - script: |
                  set -eux
                  mkdir -p artifacts
                  cp -f certifai_toolkit.zip artifacts/
                  pip install jinja2
                  ./build.sh docker
pipelines:
  cortex-certifai-examples-build:
    group: certifai
    materials:
      cortex-certifai-examples:
        git: git@github.com:CognitiveScale/cortex-certifai-examples.git
        branch: 4602-prediction-service-python38
      certifai-toolkit:
        pipeline: certifai-toolkit
        stage: build
    stages: *serviceBuild

  # TODO: Do we need a PR pipeline?
#  cortex-certifai-examples-pr:
#    group: pull-requests
#    label_template: ${COUNT}
#    materials:
#      cortex-certifai-examples:
#        plugin_configuration:
#          id: github.pr
#          version: 1
#        options:
#          url: git@github.com:CognitiveScale/cortex-certifai-examples.git
#          defaultBranch: master
#      stages: *serviceBuild
