apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{RESOURCE_NAME}}
  name: {{RESOURCE_NAME}}
  namespace: '{{NAMESPACE}}'
spec:
  ports:
    - name: {{RESOURCE_NAME}}
      port: 8551
      protocol: TCP
      targetPort: 8551
  selector:
    app: {{RESOURCE_NAME}}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{RESOURCE_NAME}}
  name: {{RESOURCE_NAME}}
  namespace: '{{NAMESPACE}}'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{RESOURCE_NAME}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{RESOURCE_NAME}}
      name: {{RESOURCE_NAME}}
      namespace: '{{NAMESPACE}}'
    spec:
      containers:
        - image: {{IMAGE_NAME}}
          imagePullPolicy: IfNotPresent
          name: {{RESOURCE_NAME}}
          ports:
            - containerPort: 8551
              protocol: TCP
          env:
            - name: HOSTED_MODEL_URL
              value: "{{HOSTED_MODEL_URL}}"
            - name: HOSTED_MODEL_AUTH_HEADER_TOKEN
              value: "{{HOSTED_MODEL_AUTH_HEADER_TOKEN}}"
            - name: MODEL_PATH
              value: "{{MODEL_PATH}}"
            - name: METADATA_PATH
              value: "{{METADATA_PATH}}"
            # Credentials if using S3 (or Minio)
            - name: BUCKET_ENDPOINT
              value: "{{BUCKET_ENDPOINT}}"
            - name: BUCKET_ACCESS_KEY
              value: "{{BUCKET_ACCESS_KEY}}"
            - name: BUCKET_SECRET_KEY
              value: "{{BUCKET_SECRET_KEY}}"
            # Credentials if using Azure Blob Storage
            - name: AZURE_ACCOUNT_NAME
              value: "{{AZURE_ACCOUNT_NAME}}"
            - name: AZURE_ACCOUNT_KEY
              value: "{{AZURE_ACCOUNT_KEY}}"
            - name: AZURE_SAS_TOKEN
              value: "{{AZURE_SAS_TOKEN}}"
            - name: AZURE_CONNECTION_STRING
              value: "{{AZURE_CONNECTION_STRING}}"
            - name: AZURE_CUSTOM_DOMAIN
              value: "{{AZURE_CUSTOM_DOMAIN}}"
            - name: AZURE_ENDPOINT
              value: "{{AZURE_ENDPOINT}}"
          resources:
            requests:
              memory: "1Gi"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30