apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-push
spec:
  params: 
  - name: image-reference
    type: string
  description: |
    This pipeline builds deployment template and pushes the image to dockerhub
  workspaces:
    - name: shared-data
  tasks:
    - name: hello
      taskRef:
        name: hello
      workspaces:
      - name: output
        workspace: shared-data
    # - name: build-push
    #   runAfter: ["hello"]
    #   taskRef:
    #     name: kaniko
    #   workspaces:
    #   - name: source
    #     workspace: shared-data
    #   params:
    #   - name: IMAGE
    #     value: $(params.image-reference)
