# An example for a model in s3 bucket
MODEL_PATH=s3://bucket/model.pkl

# S3 credentials
BUCKET_ENDPOINT=<your-s3-bucket-endpoint>
BUCKET_SECRET_KEY=<your-s3-secret-key>
BUCKET_ACCESS_KEY=<your-s3-access-key>

# GCP credentials
GOOGLE_APPLICATION_CREDENTIALS=<creds-file-path.json>

# Azure Blob store credentials
AZURE_ACCOUNT_NAME=<your-azure-account-name>
AZURE_ACCOUNT_KEY=<your-azure-account-key>
