# An example for a mojo model in s3 bucket
#MODEL_PATH=s3://bucket/pipeline.mojo

# Default location for local model
MODEL_PATH=model/pipeline.mojo

  # S3 credentials
# BUCKET_ENDPOINT=<your-s3-bucket-endpoint>
BUCKET_SECRET_KEY=<your-s3-secret-key>
BUCKET_ACCESS_KEY=<your-s3-access-key>

  # GCP credentials
GOOGLE_APPLICATION_CREDENTIALS=<creds-file-path.json>

  # Azure Blob store credentials
AZURE_ACCOUNT_NAME=<your-azure-account-name>
AZURE_ACCOUNT_KEY=<your-azure-account-key>

  # MOJO environment - Default local location
H2O_LICENSE_PATH=license/license.txt

# MOJO environment S3 Location
#H2O_LICENSE_PATH=s3://bucket/license.txt
